### ISSUE TITLE
Graspit segfaults when calling planner multiple times

### ISSUE THREAD

**Issue by jackrasiel** [graspit-simulator/graspit_interface#6]
Hi all,

Graspit segfaults when during execution of the following loop, using GraspitCommander:

```
    lots_of_runs = []
    gc = GraspitCommander
    for i in range(10):
        gc.clearWorld()
        gc.importGraspableBody("ritz_crackers")
        gc.importRobot("cobra_gripper")
        grasps = gc.planGrasps(max_steps=70000)
        lots_of_runs.append(grasps)
```

The segfault tends to occur at the second iteration, in the call to planGrasps(); however it will occasionally make it as far as five or six iterations.
The attached file contains backtraces from four separate segfaults.

Best
Jack
[graspit_interface_segfault_only.txt](https://github.com/CURG/graspit_interface/files/402311/graspit_interface_segfault_only.txt)

**Comment by jvarley** [comment]
@JSR694 I think this fixes your particular issue.  I was having the same problem.  Basically clearWorld deletes the hand.  Then the first thing planGrasps does is delete the old planner.  The old planner references the old hand and this causes a seg fault in the destructor.  I am also going to move the cleanup of the planner and handobject state to the end of planGrasps rather than calling it at the start.  

https://github.com/graspit-simulator/graspit/pull/65

And thank you for the backtraces, they were very helpful.

**Comment by jvarley** [comment]
This should fix it as well, even without the change to graspit.
https://github.com/CURG/graspit_interface/pull/7

**Comment by jackrasiel** [comment]
Thank you!  Glad I could help.
